name: jaidem
description: A new Flutter project with jaidem.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Theme
  google_fonts: ^6.1.0
  
  # Navigation
  auto_route: ^7.8.4
  
  # Network
  dio: ^5.4.0
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # Dependency Injection
  get_it: ^7.6.4
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7









dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  
  # Code Generation
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
