name: jaidem
description: A new Flutter project with jaidem.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Theme
  google_fonts: ^6.1.0
  
  # Navigation
  auto_route: ^10.1.0+1
  
  # Network
  dio: ^5.9.0
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # Dependency Injection
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code Generation
  auto_route_generator: ^10.2.3
  build_runner: ^2.4.14



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
